#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARCHIVE="${1:-$HOME/Downloads/2026-08-17-backups.tar.gz}"
OUTPUT="${2:-$ROOT_DIR/dev-seed.tar.gz}"
PG_BIN="${PG_BIN:-/usr/local/opt/postgresql@16/bin}"
PGPORT="${DEV_SEED_PGPORT:-55432}"
PROJECT_IDS="${DEV_SEED_PROJECT_IDS:-}"
PROJECT_LIMIT="${DEV_SEED_PROJECT_LIMIT:-5}"
EXPEDITIONS_PER_PROJECT="${DEV_SEED_EXPEDITIONS_PER_PROJECT:-3}"
WORKDIR="${DEV_SEED_WORKDIR:-}"
KEEP_WORKDIR="${DEV_SEED_KEEP_WORKDIR:-0}"

if [[ -z "$WORKDIR" ]]; then
  WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/geome-dev-seed.XXXXXX")"
fi

PGDATA="$WORKDIR/pgdata"
PGHOST="$WORKDIR"
BCID_DUMP="$WORKDIR/bcid.pgsql"
BISCICOL_DUMP="$WORKDIR/biscicol_all.pgsql"
OUTPUT_DIR="$WORKDIR/output"
BCID_SEED_SQL="$OUTPUT_DIR/dev-seed-bcid.sql"
BISCICOL_SEED_SQL="$OUTPUT_DIR/dev-seed-biscicol.sql"
SERVER_STARTED=0

cleanup() {
  local status=$?

  if [[ "$SERVER_STARTED" == "1" ]]; then
    "$PG_BIN/pg_ctl" -D "$PGDATA" -m fast -w stop >/dev/null 2>&1 || true
  fi

  if [[ "$KEEP_WORKDIR" != "1" ]]; then
    rm -rf "$WORKDIR"
  else
    printf 'Keeping workdir: %s\n' "$WORKDIR" >&2
  fi

  exit "$status"
}
trap cleanup EXIT

require_executable() {
  local exe="$1"
  if [[ ! -x "$exe" ]]; then
    printf 'Missing executable: %s\n' "$exe" >&2
    exit 1
  fi
}

require_executable "$PG_BIN/initdb"
require_executable "$PG_BIN/pg_ctl"
require_executable "$PG_BIN/createdb"
require_executable "$PG_BIN/dropdb"
require_executable "$PG_BIN/pg_restore"
require_executable "$PG_BIN/pg_dump"
require_executable "$PG_BIN/psql"

if [[ ! -f "$ARCHIVE" ]]; then
  printf 'Backup archive not found: %s\n' "$ARCHIVE" >&2
  exit 1
fi

mkdir -p "$WORKDIR" "$OUTPUT_DIR" "$(dirname "$OUTPUT")"

BCID_MEMBER="$(tar -tzf "$ARCHIVE" | grep -E '(^|/)bcid\.pgsql$' | head -n 1 || true)"
BISCICOL_MEMBER="$(tar -tzf "$ARCHIVE" | grep -E '(^|/)biscicol_all\.pgsql$' | head -n 1 || true)"

if [[ -z "$BCID_MEMBER" || -z "$BISCICOL_MEMBER" ]]; then
  printf 'Could not find bcid.pgsql and biscicol_all.pgsql inside %s\n' "$ARCHIVE" >&2
  exit 1
fi

printf 'Extracting dumps from %s\n' "$ARCHIVE"
tar -xOzf "$ARCHIVE" "$BCID_MEMBER" > "$BCID_DUMP"
tar -xOzf "$ARCHIVE" "$BISCICOL_MEMBER" > "$BISCICOL_DUMP"

printf 'Starting temporary PostgreSQL server on port %s\n' "$PGPORT"
"$PG_BIN/initdb" -D "$PGDATA" --no-locale --encoding=UTF8 >/dev/null
"$PG_BIN/pg_ctl" -D "$PGDATA" -o "-p $PGPORT -k $PGHOST" -l "$WORKDIR/postgres.log" -w start >/dev/null
SERVER_STARTED=1

createdb_tmp() {
  "$PG_BIN/dropdb" -h "$PGHOST" -p "$PGPORT" --if-exists "$1" >/dev/null
  "$PG_BIN/createdb" -h "$PGHOST" -p "$PGPORT" "$1"
}

createdb_tmp bcid
createdb_tmp biscicol

printf 'Restoring bcid\n'
"$PG_BIN/pg_restore" -h "$PGHOST" -p "$PGPORT" \
  --no-owner --no-privileges --clean --if-exists \
  -d bcid "$BCID_DUMP"

printf 'Restoring biscicol\n'
"$PG_BIN/pg_restore" -h "$PGHOST" -p "$PGPORT" \
  --no-owner --no-privileges --clean --if-exists -j 4 \
  -d biscicol "$BISCICOL_DUMP"

printf 'Scrubbing bcid credentials\n'
"$PG_BIN/psql" -h "$PGHOST" -p "$PGPORT" -d bcid \
  -f "$ROOT_DIR/scripts/dev-seed/dev-seed-bcid.sql"

printf 'Trimming biscicol\n'
"$PG_BIN/psql" -h "$PGHOST" -p "$PGPORT" -d biscicol \
  -v dev_seed_project_ids="$PROJECT_IDS" \
  -v dev_seed_project_limit="$PROJECT_LIMIT" \
  -v dev_seed_expeditions_per_project="$EXPEDITIONS_PER_PROJECT" \
  -f "$ROOT_DIR/scripts/dev-seed/dev-seed-biscicol.sql"

printf 'Writing seed SQL files\n'
{
  printf -- '-- GeOMe development seed generated by scripts/dev-seed/create-dev-seed.sh\n'
  printf -- '-- Source archive: %s\n\n' "$ARCHIVE"
  "$PG_BIN/pg_dump" -h "$PGHOST" -p "$PGPORT" \
    --clean --if-exists --create --no-owner --no-privileges bcid
} > "$BCID_SEED_SQL"

{
  printf -- '-- GeOMe development seed generated by scripts/dev-seed/create-dev-seed.sh\n'
  printf -- '-- Source archive: %s\n\n' "$ARCHIVE"
  "$PG_BIN/pg_dump" -h "$PGHOST" -p "$PGPORT" \
    --clean --if-exists --create --no-owner --no-privileges biscicol
} > "$BISCICOL_SEED_SQL"

printf 'Packaging %s\n' "$OUTPUT"
tar -czf "$OUTPUT" -C "$OUTPUT_DIR" dev-seed-bcid.sql dev-seed-biscicol.sql

printf 'Created %s\n' "$OUTPUT"
