#INSERT INTO table (a,b,c) VALUES (1,2,3) 
#  ON DUPLICATE KEY UPDATE c=c+1; 

DROP TABLE IF EXISTS samplesForIPT;
CREATE TABLE samplesForIPT ( 
	materialSampleID int,
	dcterms_references varchar(255),
	collectionCode varchar(255),
	associatedMedia text,
	associatedReferences text,
	associatedSequences text,
	associatedTaxa text,
	identificationRemarks text,
	basisOfRecord text,
	class text,
	coordinateUncertaintyInMeters text,
	country text,
	dateCollected text,
	dateIdentified text,
	dynamicProperties text,
	decimalLatitude text,
	decimalLongitude text,
	establishmentMeans text,
	eventRemarks text,
	family text,
	fieldNotes text,
	genus text,
	georeferenceProtocol text,
	habitat text,
	identifiedBy text,
	island text,
	islandGroup text,
	lifeStage text,
	locality text,
	maximumDepthInMeters text,
	maximumDistanceAboveSurfaceInMeters text,
	minimumDepthInMeters text,
	minimumDistanceAboveSurfaceInMeters text,
	occurrenceID text,
	occurrenceRemarks text,
	ordr text,
	phylum text,
	preparations text,
	previousIdentifications text,
	principalInvestigator text,
	recordedBy text,
	samplingProtocol text,
	sex text,
	species text,
	stateProvince text,
	subSpecies text,
	taxonRemarks text,
	vernacularName text,
	primary key (materialSampleID,dcterms_references)
);
