#INSERT INTO table (a,b,c) VALUES (1,2,3) 
#  ON DUPLICATE KEY UPDATE c=c+1; 

DROP TABLE IF EXISTS samplesForIPT;
CREATE TABLE samplesForIPT ( 
	materialSampleID varchar(255),
	collectionCode varchar(255),
	associatedMedia text,
	associatedReferences text,
	associatedSequences text,
	associatedTaxa text,
	basisOfIdentification text,
	class text,
	coordinateUncertaintyInMeters text,
	country text,
	dayCollected text,
	dayIdentified text,
	decimalLatitude text,
	decimalLongitude text,
	establishmentMeans text,
	eventRemarks text,
	extractionID text,
	family text,
	fieldNotes text,
	fundingSource text,
	geneticTissueType text,
	genus text,
	georeferenceProtocol text,
	habitat text,
	identifiedBy text,
	island text,
	islandGroup text,
	length text,
	lifeStage text,
	locality text,
	maximumDepthInMeters text,
	maximumDistanceAboveSurfaceInMeters text,
	microHabitat text,
	minimumDepthInMeters text,
	minimumDistanceAboveSurfaceInMeters text,
	monthCollected text,
	monthIdentified text,
	occurrenceID text,
	occurrenceRemarks text,
	ordr text,
	permitInformation text,
	phylum text,
	plateID text,
	preservative text,
	previousIdentifications text,
	previousTissueID text,
	principalInvestigator text,
	recordedBy text,
	sampleOwnerInstitutionCode text,
	samplingProtocol text,
	sex text,
	species text,
	stateProvince text,
	subSpecies text,
	substratum text,
	taxonRemarks text,
	tissueStorageID text,
	vernacularName text,
	weight text,
	wellID text,
	wormsID text,
	yearCollected text,
	yearIdentified text,
	primary key (collectionCode,materialSampleID)
);
